name: C Code Formatting Check

on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install clang-format
      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # Step 3: Run clang-format to check formatting
      - name: Run clang-format style check for C/C++ files
        run: |
          find . -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" | xargs clang-format --dry-run --Werror

      # Step 4: Output instructions on how to fix formatting issues
      - name: Instructions for fixing formatting issues
        if: failure()
        run: echo "Formatting issues detected. Run 'clang-format -i <file>' locally to fix."