name: C Code Formatting Check

on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  format-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run clang-format style check
      - name: Run clang-format style check for C/C++ code
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '13'
          check-path: '.'  # Checks all files in the repo
          fallback-style: 'LLVM'  # You can change this to 'Mozilla', 'Google', etc.