name: C Code Formatting Check

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install clang-format
      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # Step 3: Run clang-format to check formatting
      - name: Check C code formatting
        run: |
          clang-format --dry-run --Werror **/*.c **/*.h

      # Optional: Provide instructions on fixing formatting
      - name: Output instructions
        run: echo "Formatting issues detected. Run 'clang-format -i <file>' locally to fix."